FEATURE: UX improvements to leaderboard page
ucsb-cs156-f23/proj-happycows-f23-5pm-3 pull request #20
Opened 2023-11-18 19:19 UTC by KarimBenyassine1

## Overview
In this PR, I moved the "back" button to the top of the page and made some leaderboard improvements like removing unnecessary columns.

## Future Possibilities (Optional)
-  You can add the back button on top of the table rather than all the way to the right.

## Validation (Optional)
1. Download this branch.
2. Run the project.
3. Go to LeaderboardPage
4. Check columns and back button. 

## Tests
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
## Linked Issues
Closes #8

2023-11-21 21:19 UTC, kaitntom reviewed
LGTM! I ran this branch locally and the back button worked when I tried it.

2023-11-21 22:01 UTC, kaitntom submitted a review, later dismissed
LGTM! I ran this branch locally and the back button worked when I tried it.

2023-11-22 20:36 UTC, kellyyan approved these changes, later dismissed
LGTM

2023-11-24 21:30 UTC, pconrad commented
Please see:  https://ucsb-cs156.github.io/topics/pull_requests/#screenshots-storybook-swagger-etc and  https://ucsb-cs156.github.io/topics/pull_requests/storybook_links.html

2023-11-25 20:27 UTC, pconrad requested changes
Please help me understand how three team members looked at this PR, and thought: Yeah, looks good to me!

<img width="1014" alt="image" src="https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-3/assets/1119017/41a263a9-46e1-421b-94a8-94cb64e8832c">

The .env.SAMPLE is a very important and necessary part of the code base.  It serves an important function. Deleting it breaks the developer experience.   Please restore this file.

2023-11-26 19:00 UTC, pconrad requested changes
When removing a prop from a react component, we should probably also remove that prop from the places that component is used.

2023-11-26 19:00 UTC, pconrad commented on frontend/src/main/components/Leaderboard/LeaderboardTable.js
> +export default function LeaderboardTable({ leaderboardUsers }) {
You removed `currentUser` as a prop, which is a good thing to do.

But that suggest that it should also be removed in all of the places where `LeaderboardTable` is used.  See below.

2023-11-26 19:00 UTC, pconrad commented on frontend/src/main/pages/LeaderboardPage.js
> +              (<LeaderboardTable leaderboardUsers={userCommons} currentUser={currentUser} />) :
```suggestion
              (<LeaderboardTable leaderboardUsers={userCommons}  />) :
```

2023-11-26 19:00 UTC, pconrad commented on frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
> +          <LeaderboardTable leaderboardUsers={leaderboardFixtures.fiveUserCommonsLB} currentUser={currentUser} />
```suggestion
          <LeaderboardTable leaderboardUsers={leaderboardFixtures.fiveUserCommonsLB}  />
```

2023-11-26 21:34 UTC, pconrad approved these changes
LGTM

2023-11-27 05:01 UTC, kellyyan approved these changes
LGTM :)

2023-11-27 17:14 UTC, merged