Kaitlyn-FEATURE: Eliminate purchase notification popups
ucsb-cs156-f23/proj-happycows-f23-5pm-3 pull request #22
Opened 2023-11-21 02:07 UTC by kaitntom

## Overview

In this PR, I removed the "Cow Sold!" toast notification when a cow is sold.

## Screenshots (Optional)

Before
<img width="1792" alt="Screenshot 2023-11-20 at 5 10 30 PM" src="https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-3/assets/92133238/f462af86-45b6-42ff-8bfc-c9e68cf2c9f6">
After
<img width="1792" alt="Screenshot 2023-11-20 at 5 11 32 PM" src="https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-3/assets/92133238/a4eb173e-1f74-4373-b321-1b8af61bfbf3">

## Validation (Optional)

1. Download this branch.
2. Run the project.
3. Go to this page.
4. Test this function.

## Tests

- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 

## Linked Issues

Closes #2

2023-11-21 22:21 UTC, kellyyan commented
LGTM!

2023-11-21 22:22 UTC, kellyyan submitted a review, later dismissed
Looks good :)

2023-11-23 01:47 UTC, madisonlong1 commented
LGTM

2023-11-23 01:49 UTC, madisonlong1 submitted a review, later dismissed
LGTM

2023-11-23 20:15 UTC, pconrad commented on frontend/src/main/pages/PlayPage.js
> +//import { toast } from "react-toastify";
Please see: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2023-11-23 20:15 UTC, pconrad requested changes
Please see: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2023-11-23 20:15 UTC, pconrad commented on frontend/src/tests/pages/PlayPage.test.js
> +        //expect(mockToast).toBeCalledWith("Cow sold!");
Please see: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2023-11-23 20:28 UTC, pconrad commented on frontend/src/main/pages/PlayPage.js
> +//import { toast } from "react-toastify";
Please see: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2023-11-23 20:28 UTC, pconrad commented on frontend/src/main/pages/PlayPage.js
> +    //toast(`Cow sold!`);
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2023-11-25 20:31 UTC, pconrad approved these changes
LGTM!

2023-11-25 20:31 UTC, pconrad commented on frontend/src/tests/pages/PlayPage.test.js
> +        //expect(mockToast).toBeCalledWith("Cow sold!");
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2023-11-25 20:44 UTC, merged