Added entity and repository for Announcement
ucsb-cs156-f23/proj-happycows-f23-5pm-3 pull request #28
Opened 2023-11-25 00:48 UTC by wyatthspivak

## Overview

In this PR, I added an Announcement entity class and a AnnouncementRepository for the first part of creating backend support for a Announcements in the commons play page

## Feedback Request (Optional)

Please give suggestions on the following:
- Do the entity fields I added line up with the ones in the EPIC issue #15 ?

## Future Possibilities (Optional)

Some possible points could be:
- This is the beginning/part of having announcements in the commons play page

## Validation (Optional)

1. Download this branch.
2. Run the project.
3. Compare in code the entity fields specified in the issues 

## Tests

- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #25

2023-11-25 03:48 UTC, KarimBenyassine1 submitted a review, later dismissed
LGTM!

2023-11-25 09:56 UTC, kaitntom submitted a review, later dismissed
LGTM!

2023-11-25 20:35 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/repositories/AnnouncementRepository.java
> +public interface AnnouncementRepository extends CrudRepository<Announcement, Long> {
This needs to be annotated with the `@Repository` annotation (see the other repository classes in the same directory.

2023-11-25 20:36 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/repositories/AnnouncementRepository.java
> +
```suggestion
import org.springframework.stereotype.Repository;
```

2023-11-25 20:37 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/repositories/AnnouncementRepository.java
> +
```suggestion

@Repository
```

2023-11-25 20:37 UTC, pconrad requested changes
One small change needed.

2023-11-26 19:05 UTC, pconrad approved these changes
LGTM!

2023-11-26 19:16 UTC, merged