Karim: Farmer Greetings UI Improvement
ucsb-cs156-f23/proj-happycows-f23-5pm-3 pull request #32
Opened 2023-11-25 05:02 UTC by KarimBenyassine1

## Overview

In this PR, I changed the greetings message on the home and play page so that the fonts are smaller and there is a color gradient animation.

## Screenshots (Optional)
Be
<img width="1440" alt="Screen Shot 2023-11-24 at 8 00 43 PM" src="https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-3/assets/46539388/48247cc3-58b6-4716-87c4-c694c4b20846">
fore:
<img width="1440" alt="Screen Shot 2023-11-24 at 8 00 46 PM" src="https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-3/assets/46539388/183d08fc-cafa-4f01-948b-734180cd20ed">

After:
<img width="1440" alt="Screen Shot 2023-11-24 at 8 58 08 PM" src="https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-3/assets/46539388/930d7897-b7d1-47a7-a607-eb4888490891">
<img width="1440" alt="Screen Shot 2023-11-24 at 8 57 58 PM" src="https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-3/assets/46539388/997cc3c8-0aaf-4cbc-b1bf-a5e51a8552b8">

## Feedback Request (Optional)

Please give suggestions on the following:
- This method might not be the best way to do things. What do you think?
- The way this is implemented is the best I can think of. Is it acceptable?
- Where should these things go? I put them here, but it feels out of place.

## Future Possibilities (Optional)
- Cooler, eye-catching greeting animation

## Validation (Optional)

1. Download this branch.
2. Run the project.
3. Go to HomePage and PlayPage.
4. Check greetings header and whether it fits requirements.

## Tests

- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 

## Linked Issues

Closes #5

2023-11-25 09:53 UTC, kaitntom submitted a review, later dismissed
LGTM! The animation and green color really stand out!

2023-11-26 19:13 UTC, pconrad commented
The animation is nice!

I wonder about the contrast with the backgrounds though.  Looking at this in the context of the backgrounds (via the storybook), it's kind of hard to read, and I wonder whether this is an improvement?

![home-page](https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-3/assets/1119017/d81840ad-0c1d-4055-b5d3-84d3178d6922)

Some possible solutions would be to add a background color to make the green text pop?  It might be opaque, or have  partial alpha transparency so that the background shows through a bit, but there's enough contrast that the words can be read easily.

2023-11-26 19:15 UTC, pconrad requested changes
The code looks fine, and the animation is nice.

However, in context, the text is hard to read against the background; see the animation I linked to in an earlier comment.

Please add links to the storybook in the description, and show screenshots that show the text against all of the backgrounds.   

Also: please make adjustments so that the text can be easily read against all of the backgrounds.

2023-11-26 21:31 UTC, pconrad commented on frontend/src/main/pages/HomePage.css
> +.gradient-animation {
There is a better place to put CSS, but we'll leave cleaning that up to another PR.

2023-11-26 21:31 UTC, pconrad approved these changes
LGTM

2023-11-26 21:32 UTC, merged